// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPSqU5cMZpNzgHlwzzaNTpmycBS1pGEKU',
    appId: '1:319769369149:web:5e6882e04a628837e5a854',
    messagingSenderId: '319769369149',
    projectId: 'case-study-88de7',
    authDomain: 'case-study-88de7.firebaseapp.com',
    storageBucket: 'case-study-88de7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwSt_Lh7hdj1M2tb4PaeGkxGj7tbWEg0',
    appId: '1:319769369149:android:7cf6e589aa523443e5a854',
    messagingSenderId: '319769369149',
    projectId: 'case-study-88de7',
    storageBucket: 'case-study-88de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURsMMSdnIOyqU48UreWTzjJpI72rfuWI',
    appId: '1:319769369149:ios:b4162ace9bf99c26e5a854',
    messagingSenderId: '319769369149',
    projectId: 'case-study-88de7',
    storageBucket: 'case-study-88de7.appspot.com',
    iosBundleId: 'com.example.caseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURsMMSdnIOyqU48UreWTzjJpI72rfuWI',
    appId: '1:319769369149:ios:5907a5da8d59140ee5a854',
    messagingSenderId: '319769369149',
    projectId: 'case-study-88de7',
    storageBucket: 'case-study-88de7.appspot.com',
    iosBundleId: 'com.example.caseStudy.RunnerTests',
  );
}
